/****************************************************************************
 *
 * Copyright 2016 Samsung Electronics All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 *
 ****************************************************************************/


/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <tinyara/config.h>

#include <sys/types.h>
#include <sys/statfs.h>
#include <sys/stat.h>

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <assert.h>
#include <errno.h>
#include <debug.h>

#include <tinyara/kmalloc.h>
#include <tinyara/fs/fs.h>
#include <tinyara/fs/procfs.h>
#include <tinyara/version.h>

#if defined(CONFIG_AUDIO_NDP120) && !defined(CONFIG_DISABLE_MOUNTPOINT) && defined(CONFIG_FS_PROCFS)
#include <syntiant_ilib/syntiant_ndp_ilib_version.h>
#include <syntiant_ilib/syntiant_ndp120_driver.h>
#include <ndp120_voice.h>

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/
/* Determines the size of an intermediate buffer that must be large enough
 * to handle the longest line generated by this logic.
 */

#define NDP120_PROC_OUTPUT_LINELEN 64
/****************************************************************************
 * Private Types
 ****************************************************************************/

/* This structure describes one open "file" */

struct ndp120_proc_file_s {
    struct procfs_file_s base;	/* Base open file structure */
    unsigned int linesize;		/* Number of valid characters in line[] */
    char line[NDP120_PROC_OUTPUT_LINELEN];	/* Pre-allocated buffer for formatted lines */
};

/****************************************************************************
 * Private Function Prototypes
 ****************************************************************************/

/* File system methods */

static int ndp120_proc_open(FAR struct file *filep, FAR const char *relpath, int oflags, mode_t mode);
static int ndp120_proc_close(FAR struct file *filep);
static ssize_t ndp120_proc_read(FAR struct file *filep, FAR char *buffer, size_t buflen);

static int ndp120_proc_dup(FAR const struct file *oldp, FAR struct file *newp);

static int ndp120_proc_stat(FAR const char *relpath, FAR struct stat *buf);

/****************************************************************************
 * Private Variables
 ****************************************************************************/

/****************************************************************************
 * Public Variables
 ****************************************************************************/

/* See fs_mount.c -- this structure is explicitly externed there.
 * We use the old-fashioned kind of initializers so that this will compile
 * with any compiler.
 */

const struct procfs_operations ndp120_proc_operations = {
    ndp120_proc_open,				/* open */
    ndp120_proc_close,				/* close */
    ndp120_proc_read,				/* read */
    NULL,						 	/* write */

    ndp120_proc_dup,				/* dup */

    NULL,							/* opendir */
    NULL,							/* closedir */
    NULL,							/* readdir */
    NULL,							/* rewinddir */
    ndp120_proc_stat				/* stat */
};

/****************************************************************************
 * Private Functions
 ****************************************************************************/

/****************************************************************************
 * Name: ndp120_proc_open
 ****************************************************************************/

static int ndp120_proc_open(FAR struct file *filep, FAR const char *relpath, int oflags, mode_t mode)
{
    FAR struct ndp120_proc_file_s *attr;

    fvdbg("Open '%s'\n", relpath);

    /* PROCFS is read-only.  Any attempt to open with any kind of write
     * access is not permitted.
     *
     * REVISIT:  Write-able proc files could be quite useful.
     */

    if ((oflags & O_WRONLY) != 0 || (oflags & O_RDONLY) == 0) {
        fdbg("ERROR: Only O_RDONLY supported\n");
        return -EACCES;
    }

    /* "ndp120" is the only acceptable value for the relpath */

    if (strcmp(relpath, "ndp120") != 0) {
        fdbg("ERROR: relpath is '%s'\n", relpath);
        return -ENOENT;
    }

    /* Allocate a container to hold the file attributes */

    attr = (FAR struct ndp120_proc_file_s *)kmm_zalloc(sizeof(struct ndp120_proc_file_s));
    if (!attr) {
        fdbg("ERROR: Failed to allocate file attributes\n");
        return -ENOMEM;
    }

    /* Save the attributes as the open-specific state in filep->f_priv */

    filep->f_priv = (FAR void *)attr;
    return OK;
}

/****************************************************************************
 * Name: ndp120_proc_close
 ****************************************************************************/

static int ndp120_proc_close(FAR struct file *filep)
{
    FAR struct ndp120_proc_file_s *attr;

    /* Recover our prsivate data from the struct file instance */

    attr = (FAR struct ndp120_proc_file_s *)filep->f_priv;
    DEBUGASSERT(attr);

    /* Release the file attributes structure */

    kmm_free(attr);
    filep->f_priv = NULL;
    return OK;
}

/****************************************************************************
 * Name: ndp120_proc_read
 ****************************************************************************/

#define ADD_LINE(...) {\
    linesize = snprintf(attr->line, NDP120_PROC_OUTPUT_LINELEN, __VA_ARGS__);\
    copysize = procfs_memcpy(attr->line, linesize, buffer, remaining, &offset);\
    totalsize += copysize;\
    buffer += copysize;\
    remaining -= copysize;\
    if (totalsize >= buflen) {\
        goto end;\
    }\
}

extern struct ndp120_dev_s * ndp120_get_debug_handle(void);

static ssize_t ndp120_proc_read(FAR struct file *filep, FAR char *buffer, size_t buflen)
{
    FAR struct ndp120_proc_file_s *attr;
    size_t remaining;
    size_t linesize;
    size_t copysize;
    size_t totalsize;
    off_t offset;
    int i, s;
    ndp120_dsp_counters_t dsp_cnts;
    static int cnt = 0;

    fvdbg("buffer=%p buflen=%d\n", buffer, (int)buflen);

    /* Recover our private data from the struct file instance */

    attr = (FAR struct ndp120_proc_file_s *)filep->f_priv;
    DEBUGASSERT(attr);

    if (filep->f_pos == 0) {
         cnt++;
    }

    offset = filep->f_pos;
    remaining = buflen;
    totalsize = 0;

    struct ndp120_dev_s *ndp_debug_handle  = ndp120_get_debug_handle();
    if (!ndp_debug_handle) {
        goto end;
    }

    ADD_LINE("FW Loaded: %d\n", ndp_debug_handle->fw_loaded);

    struct syntiant_ndp_device_s *ndp = ndp_debug_handle->ndp;
    if (!ndp) {
        goto end;
    }

    ADD_LINE("ilib: %s\n", SYNTIANT_NDP_ILIB_RELEASE_HASH);

    uint8_t ndp_spi_reg;
    int spi_regs_to_read[] = {0,1,2,3,4,5,0x10,0x11,0x12};
    ADD_LINE("SPI regs\n");
    for (i = 0; i < sizeof(spi_regs_to_read)/sizeof(spi_regs_to_read[0]); i++) {
        syntiant_ndp120_read(ndp, 0, spi_regs_to_read[i], &ndp_spi_reg);
        ADD_LINE("0x%02X = 0x%02X\n", spi_regs_to_read[i], ndp_spi_reg);
    }

    s = syntiant_ndp120_get_dsp_counters(ndp, &dsp_cnts);
    if (s) {
        ADD_LINE("ERROR Getting DSP counters: %d\n", s);
    }
    ADD_LINE("frame_cnt: %d\n", dsp_cnts.frame_cnt);
    ADD_LINE("dnn_int_cnt: %d\n", dsp_cnts.dnn_int_cnt);
    ADD_LINE("dnn_err_cnt: %d\n", dsp_cnts.dnn_err_cnt);
    ADD_LINE("dnn_run_err_cnt: %d\n", dsp_cnts.dnn_run_err_cnt);
    ADD_LINE("pcm_debug_cnt: %d\n", dsp_cnts.pcm_debug_cnt);
    ADD_LINE("func_debug_cnt: %d\n", dsp_cnts.func_debug_cnt);
    ADD_LINE("mem_alloc_err_cnt: %d\n", dsp_cnts.mem_alloc_err_cnt);

    syntiant_ndp120_config_tank_t tank_config;
    memset(&tank_config, 0, sizeof(tank_config));
    tank_config.get = 1;
    s = syntiant_ndp120_config_dsp_tank_memory(ndp, &tank_config);
    if (s) {
        ADD_LINE("ERROR Getting Tank config: %d\n", s);
    }
    ADD_LINE("NDP120 Tank memory type: %s\n", tank_config.sampletank_mem_type == 1? "HEAP": "DNN");
    ADD_LINE("NDP120 Tank size (ms)  : %d\n", tank_config.sampletank_msec);

    ADD_LINE("KD Enabled: %d\n",ndp_debug_handle->kd_enabled);
    ADD_LINE("Sample ready count: %u\n", ndp_debug_handle->sample_ready_cnt);
    ADD_LINE("Last Sample Ready at:\n");
    for (i = 0; i < sizeof(ndp_debug_handle->last_sample_int) / sizeof(ndp_debug_handle->last_sample_int[0]); i++) {
        ADD_LINE("                      %u\n",ndp_debug_handle->last_sample_int[i]);
    }
    ADD_LINE("Last Sample wait at:\n",ndp_debug_handle->last_sample_wait_start);
    for (i = 0; i < sizeof(ndp_debug_handle->last_sample_wait_start) / sizeof(ndp_debug_handle->last_sample_wait_start[0]); i++) {
        ADD_LINE("                      %u\n",ndp_debug_handle->last_sample_wait_start[i]);
    }

    ADD_LINE("Sample ready enable at : %u\n", ndp_debug_handle->last_sample_rdy_ena);
    ADD_LINE("Sample ready disable at: %u\n", ndp_debug_handle->last_sample_rdy_dis);

    uint32_t bufwrptr1[NDP120_DSP_CONFIG_BUFCURWRPTR_COUNT];
    uint32_t bufwrptr2[NDP120_DSP_CONFIG_BUFCURWRPTR_COUNT];
    for (i = 0; i < 3; i++) {
        syntiant_ndp120_read(ndp, 1, NDP120_DSP_CONFIG_BUFCURWRPTR(i), &bufwrptr1[i]);
    }
    usleep(10);
    for (i = 0; i < 3; i++) {
        syntiant_ndp120_read(ndp, 1, NDP120_DSP_CONFIG_BUFCURWRPTR(i), &bufwrptr2[i]);
    }

    for (i = 0; i < 3; i++) {
        ADD_LINE("BUFCURWRPTR[%d]: 0x%X -> 0x%X\n", i, bufwrptr1[i], bufwrptr2[i]);
    }

#if 0
    /* debug =>  this will force aliveness check to fail */
    if (cnt == 10) {
        uint32_t dsp_cfg;
        struct syntiant_ndp_device_s *ndp = ndp_debug_handle->ndp;
        syntiant_ndp120_read(ndp, 1, NDP120_CHIP_CONFIG_DSP_CFG, &dsp_cfg);
        dsp_cfg = NDP120_CHIP_CONFIG_DSP_CFG_RUN_STALL_MASK_INSERT(dsp_cfg, 1);
        syntiant_ndp120_write(ndp, 1, NDP120_CHIP_CONFIG_DSP_CFG, dsp_cfg);
    }
#endif

end:
    if (totalsize > 0) {
        filep->f_pos += totalsize;
    }

    return totalsize;
}

/****************************************************************************
 * Name: ndp120_proc_dup
 *
 * Description:
 *   Duplicate open file data in the new file structure.
 *
 ****************************************************************************/

static int ndp120_proc_dup(FAR const struct file *oldp, FAR struct file *newp)
{
    FAR struct ndp120_proc_file_s *oldattr;
    FAR struct ndp120_proc_file_s *newattr;

    fvdbg("Dup %p->%p\n", oldp, newp);

    /* Recover our private data from the old struct file instance */

    oldattr = (FAR struct ndp120_proc_file_s *)oldp->f_priv;
    DEBUGASSERT(oldattr);

    /* Allocate a new container to hold the task and attribute selection */

    newattr = (FAR struct ndp120_proc_file_s *)kmm_malloc(sizeof(struct ndp120_proc_file_s));
    if (!newattr) {
        fdbg("ERROR: Failed to allocate file attributes\n");
        return -ENOMEM;
    }

    /* The copy the file attributes from the old attributes to the new */

    memcpy(newattr, oldattr, sizeof(struct ndp120_proc_file_s));

    /* Save the new attributes in the new file structure */

    newp->f_priv = (FAR void *)newattr;
    return OK;
}

/****************************************************************************
 * Name: ndp120_proc_stat
 *
 * Description: Return information about a file or directory
 *
 ****************************************************************************/

static int ndp120_proc_stat(const char *relpath, struct stat *buf)
{
    /* "ndp120" is the only acceptable value for the relpath */

    if (strcmp(relpath, "ndp120") != 0) {
        fdbg("ERROR: relpath is '%s'\n", relpath);
        return -ENOENT;
    }

    /* "ndp120" is the name for a read-only file */

    buf->st_mode = S_IFREG | S_IROTH | S_IRGRP | S_IRUSR;
    buf->st_size = 0;
    buf->st_blksize = 0;
    buf->st_blocks = 0;
    return OK;
}

/****************************************************************************
 * Public Functions
 ****************************************************************************/

#endif							/* !CONFIG_DISABLE_MOUNTPOINT && CONFIG_FS_PROCFS */
